Return structured success/error json responses
EyeSeeTea/FIRE-MockServer pull request #10
Opened 2017-07-07 10:47 UTC by tokland

Closes #7 

(depends on #9)

2017-07-07 15:03 UTC, adrianq approved these changes
@tokland Looks great as usual! :) Just a single comment, what do you think about adding in the doc a few examples with different responses and a very brief description of the response structure?

@ifoche you said the Angular call you finally used was slightly different, right? Do you maybe wanna add a commit to this PR and correct the docu?

2017-07-17 06:16 UTC, ifoche requested changes
@tokland it's a minimum change what I'm asking for...only a typo. Thank you very much!

2017-07-17 06:16 UTC, ifoche commented on test_fire.py
> +        res = self.request("GET", '/thisEndPointThoseNotExist')
I guess it's a typo and should read '/thisEndPointDoesNotExist' right?

2017-07-17 07:49 UTC, ifoche approved these changes
Thanks @tokland

2017-07-17 07:53 UTC, merged